name: teoremas
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - flake8
  - pytest
  - matplotlib
  - numpy
  - pandas
  - plotly
  - psutil
  - scipy
  - scikit-learn
  - sympy
  - pip:
    - bit
