name: teoremas
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - matplotlib
  - numpy
  - pandas
  - plotly
  - psutil
  - scipy
  - scikit-learn
  - sympy
  - pip
  - pip:
      - bit
