name: teoremas
channels:
  - conda-forge
  - defaults
dependencies:
  - python  # pega a última versão disponível
  - pip
  - flake8
  - pytest
  - pip:
    - some-pip-package  # substitua por pacotes pip reais que usar
