name: teoremas
channels:
  - conda-forge
  - defaults
dependencies:
  - python            # pega a última versão disponível
  - pip
  - flake8
  - pytest
  - pip:
      - requests      # exemplo de pacote pip real, pode alterar ou remover
