name: Conda Python Package CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Miniconda (Miniforge3)
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Miniforge3
        python-version: 3.11
        channels: conda-forge,defaults
        auto-update-conda: true
        auto-activate-base: false
        use-mamba: true

    - name: Clean conda cache
      run: conda clean --all --yes

    - name: Remove existing conda environment if exists
      shell: bash -l {0}
      run: conda env remove -n teoremas -y || true

    - name: Create conda environment from environment.yml
      shell: bash -l {0}
      run: mamba env create -f environment.yml

    - name: Activate environment and run tests
      shell: bash -l {0}
      run: |
        conda activate teoremas
        pytest
